### PR TITLE
fix: Fix retry logic, if retries passed is 0, we should not retry at all.

### PR DESCRIPTION
**Pull request by ryan-gang**
```
[stage-113] Getting key baz
[stage-113] replica: $ redis-cli GET baz
[stage-113] replica: Sent bytes: "*2\r\n$3\r\nGET\r\n$3\r\nbaz\r\n"
[stage-113] replica: Received RESP value: "789"
[stage-113] Retrying... (1/5 attempts)
[stage-113] replica: $ redis-cli GET baz
[stage-113] replica: Sent bytes: "*2\r\n$3\r\nGET\r\n$3\r\nbaz\r\n"
[stage-113] replica: Received RESP value: "789"
[stage-113] Received "789"
[stage-113] Test passed.
[stage-113] Terminating program
[stage-113] Program terminated successfully
```

### CODE REVIEW

**Comment by rohitpaulk** [comment]
@ryan-gang how come this doesn't affect fixtures? 🤔

**Comment by rohitpaulk** [comment]
https://github.com/codecrafters-io/redis-tester/blob/5a444d05237fabd929821a299f76de17cc1bad07/internal/test_helpers/fixtures/repl-wait/pass#L520 should go away then?

**Review by rohitpaulk — CHANGES_REQUESTED** [review]
Added a question

**Comment by ryan-gang** [comment]
It affects the fixtures @rohitpaulk.
In stage-26 (Command Processing).
Those retrying parts would go away.

**Comment by rohitpaulk** [comment]
@ryan-gang then how come tests don't fail here? The fixtures still have the retrying lines, I don't see updated fixtures in this PR

**Review by rohitpaulk — APPROVED** [review]

**Pull request merged**
